### ISSUE TITLE
Create a package for opencv 3.3.0 for python 2.7 on windows

### ISSUE THREAD

**Issue by alxg1** [conda-forge/opencv-feedstock#102]
Currently there are only 3.3.0 python 2.7 packages for linux and osx

**Comment by alxg1** [comment]
Just saw this https://github.com/conda-forge/opencv-feedstock/issues/71
Guess I'm out of luck then? Or is there any other solution short of switching to linux, considering we're on python 2.7 and need at least opencv 3.3.0?

**Comment by jakirkham** [comment]
Sorry. Since upstream won’t commit to supporting it, we can’t either. VS2008 is a painfully old target to remain compatible with.

Would encourage you to start moving to Python 3 as soon as possible. The writing is on the wall for Python 2. In 2020 (2 yrs) support will be dropped for Python 2. Some projects have already stopped supporting Python 2 or will do so even sooner than that deadline.

Not to mention, UCRT is in much better shape than any of the previous runtimes. The compatibility guarantees it make significantly improve the developer experience. Not to mention all the neat new C++ features included.
