### ISSUE TITLE
Build OpenCV with CUDA and OpenCL by default

### ISSUE THREAD

**Issue by farleylai** [conda-forge/opencv-feedstock#109]
I noticed that CUDA and OpenCL are disabled in `build.sh.` This issue is intended to figure out the difficulty of building OpenCV with hardware acceleration by default since nowadays, most serious stuff cannot be done without utilizing those heterogeneous computing cores. Other conda packages such as pytorch explicitly provides two versions of distributions w/ and w/o cuda. There should be no issue even if cuda is not available on the target machine. At least, in contrast with Windows machines, support for OpenCL on macOS machines is quite [standard](https://support.apple.com/en-us/HT202823).

Therefore, what limits the OpenCV distributions to CPU only builds?

**Comment by msarahan** [comment]
The most common limitation is that the free CI services that conda-forge is based on do not provide hardware support for these extensions.  With most packages, you can still build stuff OK, but you can't test it.  That's not really a viable path without testing.

The GPU builds that otherwise exist are typically either repackaging of upstream binaries (e.g. tensorflow) or are built by Anaconda on their GPU machines.

The infrastructure for testing packages against GPUs needs a lot of improvement.

**Comment by farleylai** [comment]
If I understand correctly, this is not a technical issue but a funding issue. If no free CI with CUDA/OpenCL support is available, have you considered to initiate a crowd-funding project for donations?

**Comment by msarahan** [comment]
I don't think it's that simple.  I don't know of major CI services that provide GPU workers.  At Anaconda, we have an internal system built around Concourse.  We can't offer that for outside use because its current instance is behind too much security stuff (providing security guarantees for our customers.)  We can provide other instances, but then there's still quite a lot more development required to make it nice for conda-forge.  It's just a very different system, unfortunately.  If 

So, it is a matter of funding sort of, but more one of time - who has the time to implement new infrastructure for conda-forge?  If companies could get together and pool to support someone's time, that might be the best.  If you'd like to contribute your time, your efforts would also be most welcome.

Links for your perusal:
TravisCI (no support seemingly): https://github.com/travis-ci/travis-ci/issues/5911 - this is used for Mac, and probably doesn't matter much.
CircleCI (some support): https://circleci.com/docs/2.0/gpu/  - this one is what we use for Linux, and thus matters the most.
Appveyor (building OK, but not clear how to test with GPU hardware): https://www.olegtarasov.me/build-cuda-projects-with-appveyor/

**Comment by jakirkham** [comment]
Could I ask that we move this conversation to issue ( https://github.com/conda-forge/conda-forge.github.io/issues/63 )? There's already been a fair bit of discussion on GPUs and CIs there. Would be great to have this information in one place.

**Comment by farleylai** [comment]
Sure, that looks more like the right place to go to.

**Comment by jakirkham** [comment]
Thanks all. :)

**Comment by apatsekin** [comment]
Sorry for opening and old issue, but can we revisit Cuda build for OpenCV? I think things changed since 2018. Conda-forge actively maintains major CV/ML libraries delivering cuda builds for: tensorflow, pytorch, mmcv - and this is really great and super useful. What blockers do we have to go the same route with OpenCV?

**Comment by jakirkham** [comment]
@apatsekin, could you please raise this as a new issue?
