### ISSUE TITLE
opencv should not depend on python

### ISSUE THREAD

**Issue by 183amir** [conda-forge/opencv-feedstock#17]
`bob.ip.flandmark` uses `opencv2`'s C/C++ code and not its python bindings but `opencv` here depends on `python`. Hence, I am unable to package `bob.ip.flandmark` with `opencv 2` for `python 3`.

**Comment by patricksnape** [comment]
Yeah that is a hard one. We would need two packages because OpenCV doesn't have a compartmentalised build.

**Comment by 183amir** [comment]
extra info: It is blocking this pull here: https://github.com/conda-forge/staged-recipes/pull/483

**Comment by patricksnape** [comment]
How would you suggest we fix this though? For example, Homebrew allows you to build without Python but if you just download the default bottle it comes with Python. Since we don't have a "build rather than just download" option in conda I don't see how we get around this. Unless we add something like `python-opencv` as the OpenCV with Python - but that seems a bit horrible - what about all the other bindings like Java etc? What if someone wants those, are we going to end up with `java-opencv` and then `java-python-opencv` or something?

**Comment by 183amir** [comment]
I think you can do it using our build matrix. So we will have `opencv_2.0.0_0` and `opencv_2.0.0_py27_0`.

**Comment by patricksnape** [comment]
But how would specify which version you want? Specifying the exact version string to get Python is not very nice/friendly/intuitive.

**Comment by 183amir** [comment]
We'll have to think about how we want to do this, right now I'm just suggesting ideas.

**Comment by patricksnape** [comment]
I agree, seems like this is on the same lines of the broader issue of how we deal with things like package name clashes across different ecosystems.

**Comment by 183amir** [comment]
Usually you need to use `features` and a meta-package that tracks that `feature` in order to do that.

**Comment by jakirkham** [comment]
We could override the build string. Still a bit nasty, but one does just install `opencv` then.

**Comment by zwn** [comment]
Not knowing much about the specific issues wrt conda build and opencv, as a user I'd like to have `opencv` package containing just opencv and `python-opencv` package with the python bindings (depending on the opencv package).

What would it take to get to that?

**Comment by patricksnape** [comment]
I don't think that is possible. Because I don't think OpenCV provides a build solution that enables you to build the Python bindings separately and link to an existing set of pre-built OpenCV libraries. You need to build everything twice.

**Comment by zwn** [comment]
So, can we build everything twice but in the `opencv` case package just the opencv libraries (the stuff that goes into `bin`) and in the `python-opencv` package just the python extension?

**Comment by patricksnape** [comment]
And what happens when I install opencv and then install python opencv after? What if I remove opencv? It will delete the shared files that were overwritten. What if the two packages are different versions? There's no scope for mutually exclusive packages in conda at the moment.

**Comment by zwn** [comment]
Package `python-opencv` should depend on package `opencv`. If you remove `opencv` then `python-opencv` will be broken as expected because of missing dependency. I don't see any shared files anywhere and certainly no overwriting. Just one dynamic library in one package and another one in a different package. The linking is done at runtime anyway, is it not?

I am not sure about versioning since I don't know enough about conda. Can the dependency in conda be versioned? If so, then `python-opencv` 3.2.x can depend on `opencv` 3.2.x. But I am not sure if I am not reinventing the wheel here - even regular python packages can have versioned dependencies.

**Comment by patricksnape** [comment]
OpenCV is extremely difficult to build, particularly on Windows, and I would not want to support two sets of recipes for building opencv twice.

The only way to support this at the moment would involve a number of nasty hacks (either overriding build strings are effectively duplicating the recipe with more flags) which I would not be willing to support. However, if someone else wanted to maintain this setup then I am open to contributions.

**Comment by jakirkham** [comment]
IIRC it might be possible in a future version of `conda-build` to generate multiple artifacts (packages) from the same build. In that case, we might be able to solve this in the same OpenCV build, but this would depend on `conda-build` 3. IIRC @mingwandroid @msarahan were working on this sort of feature. Perhaps they can elaborate on how this would work so we can see if it is applicable for this case.

**Comment by mingwandroid** [comment]
Here is an example of sub-packages (sometimes called split packages .. we should standardise the name on one or the other). They're available in recent conda-build 2 releases, but are much more powerful in conda-build 3 as they can be combined with build customisation and allow pinnings to be inherited. Fancy!

https://github.com/mingwandroid/conda-recipes/tree/master/xgboost

**Comment by jakirkham** [comment]
> They're available in recent conda-build 2 releases, but are much more powerful in conda-build 3...

Ah ok. Sorry for the misinformation. Thanks for correcting me, @mingwandroid.

**Comment by mingwandroid** [comment]
NP, I think they're only marginally interesting in conda-build 2 anyway; you couldn't do intradependencies until 3 for example, which is, IMHO one of the most important aspects of a split package.

**Comment by patricksnape** [comment]
Wow that is super fancy! Is there documentation for this stuff/more examples maybe? Do you think that we should wait for conda-build 3? What do you mean by 'intradependencies'? As in, a 'sub' package depending on the 'super' package? Also, what is this fancy [`pin_subpackage`](https://github.com/mingwandroid/conda-recipes/blob/master/xgboost/meta.yaml#L33) magic?

**Comment by jakirkham** [comment]
I'm guessing by intradependencies we are referring to artifacts from the same build depending on each other. As an example from our case would be `opencv-python` depends on `opencv-cpp` and `opencv` is a metapackage depending on both. Assuming we went with that structure and naming.

**Comment by mingwandroid** [comment]
`pin_subpackage` is what creates the intradependencies here, you can specify how tight you want them with `min_pin` and `max_pin` or you can (and I think that would be most frequent) use exact pinning (certainly in cases like this when you have a C/C++ library, `libxgboost` that is a dependency of a Python module and an R library).

For naming, this is something that we should try to standardise on. Continuum have a plan for 'ecosystem namespaces' that will allow transitioning Python packages to be named as `py-thing` which fits in with what we do for R libraries; `r-thing`. Then, naturally from that, I prefer `libthing` for the C/C++ level parts (though it could lead to liblibthing in some cases, but we could just have a rule of 'no liblib', but then again, `liblib` is more consistent when the project name begins with lib).

**Comment by mingwandroid** [comment]
Sub-packages can depend on each other, not just the super-package, and in this case, I don't even have a super-package.

**Comment by mingwandroid** [comment]
Oh yeah, all this ties in with build matrices too: https://github.com/mingwandroid/conda-recipes/blob/master/xgboost/conda_build_config.yaml

I call conda-build once and get 1 system level package, 3 python packages and one R package (some time later).

**Comment by mingwandroid** [comment]
The docs PR is here: https://github.com/conda/conda-docs/pull/414 .. this stuff will be so nice, thanks @msarahan!

**Comment by patricksnape** [comment]
Just read the documentation - that is a huge change to conda build - must have taken a lot of thought and effort - so thanks for that!

**Comment by mingwandroid** [comment]
@patricksnape, it would be great, if you had time, to play with the latest conda-build master branch and try {split,sub}-package builds of OpenCV to help to shake out any bugs in this.

Boost is another package off the top of my head that would greatly benefit from this, because currently the C++ side is rebuilt for each Python version and that only needs to happen on Windows. I am not sure how sympathetic the boost build system would be towards this though.

**Comment by jakirkham** [comment]
We already split Boost in conda-forge. There is a `boost-cpp` package for the non-Python parts. The `boost` package then depends on `boost-cpp` and builds the Python and NumPy support.

**Comment by mingwandroid** [comment]
Interesting, thanks @jakirkham. Out of interest, why `boost-cpp`? I assume here `cpp` means it has been written (mostly?) in C++?

IMHO that's not a great choice for the following reasons:

1. There's precedent in conda (and has been for a long time) for using prefixes instead of suffixes (`r-thing`) to denote ecosystem.
2. There's huge precedent for using `lib` prefixes for system level libraries.
3. `cpp` stands for 'C pre-processor' most commonly.

**Comment by stefanseefeld** [comment]
@mingwandroid, it's possible to build *just* Boost.Python using `./b2 --with-python`. It's also possible to build both, the Python2 and Python3 versions of Boost.Python in the same process (by including e.g.
```
using python : 2.7 ;
using python : 3.5 ;
```
in the user-config.jam file.

**Comment by jakirkham** [comment]
Sorry for the long delay responding to this, @mingwandroid.

As far as the `boost` naming split goes, one of our contributors was motivated to get this done and proposed this split and naming. Since there was no real opposition and some people were actually ok with it, that is what happened. I guess in this way conda-forge is the Wild West. :cowboy_hat_face:

Perhaps prefixing would be better, I think he just wanted to make it clear this was a `boost` package primarily and then note that it was C++ components only. Though you would have to ask him.

As for `lib`, IMHO `libboost` and `boost` would be confusing. All of Boost is libraries, so what is the difference between the two? I would be unable to guess that `libboost` means just C++. Probably would assume that `boost` was unchanged, but still a bit strange, no?

Could go either way on `cxx` or `cpp`. As `cpp` is a common C++ file extension, I think this is pretty safe.

There are some other points that you didn't raise that did get discussed like having `boost-python`. Admittedly this would be pretty clear, but then there is an interesting question. We don't want to break with `defaults` right. So what do we do? Have `boost-cpp` as well and then make `boost` a metapackage? Seems like extra maintenance for not much gain.

That all being said, if there is a strong motivator for restructuring, we can discuss this further. Probably best to add it as an issue on the [`boost` feedstock]( https://github.com/conda-forge/boost-feedstock ) though.

xref: https://github.com/conda-forge/boost-feedstock/issues/1
xref: https://github.com/conda-forge/staged-recipes/pull/1887

**Comment by jakirkham** [comment]
FWIW `defaults` went with `py-opencv` for the Python parts and `libopencv` for the C++ parts with `opencv` acting as a metapackage pulling in both.

**Comment by hajapy** [comment]
> FWIW defaults went with py-opencv for the Python parts and libopencv for the C++ parts with opencv acting as a metapackage pulling in both.

That seems like the right approach to me. I am unfamiliar with metapackages, though I'd be willing to give it a shot following the example https://github.com/AnacondaRecipes/opencv-feedstock/blob/master/recipe/meta.yaml.

**Comment by mingwandroid** [comment]
Great, please do! That recipe isn't the best exposition of using split-packages. This is due to the way OpenCV's CMake setup allows for passing two python interpreters in to build against. If it allowed any number then we'd have a *much* cleaner and faster to build recipe here.

I rely on CMake's caching and run CMake multiple times (once in build.sh then in each call to install-py.sh). It kind of works but I have to do some ugly calls to `sed` because some Makefiles are not updated correctly. Probably some things get built twice on some OSes but I'm not sure on that. We have `ccache` packages, are they used in builds for this kind of thing? It may be worth investigating.

An alternative would be to rework OpenCV's Python stuff so that any number of Python versions can be built against at once. That should allow removing the nasty install scripts altogether and replacing them with simple file lists instead.

Still, provided it doesn't exceed the build times, I hope our AD recipe is "good enough".

**Comment by farleylai** [comment]
By installing `opencv` through `conda`, `cv2` is provided in Python to import.
However, some `pip` package such as `mmdetection` that requires `opencv-python` would have `pip` detecting `opencv` installed by `conda` such that `opencv-python` is installed side by side with both `opencv`.

```
opencv                    4.1.1            py37ha799480_1    conda-forge
opencv-python             4.1.1.26                 pypi_0    pypi
```

Is it intended and necessary?

**Comment by hmaarrfk** [comment]
No, but maybe we can create an opencv-python package just to avoid that
issue. Can you please open an other issue for this?

Since this issue would presumably also affect the default anaconda install,
the Anaconda team might be interested in helping us find a good solution
for this.

**Comment by farleylai** [comment]
@hmaarrfk 
Created #188 FYI

**Comment by hmaarrfk** [comment]
If you can depend on qt 5.12 then this issue is closed. I don't have the bandwidth to create a 5.9 build now that the qt migration is well underway
