### ISSUE TITLE
opencv installation error

### ISSUE THREAD

**Issue by Krisanu029** [conda-forge/opencv-feedstock#218]
![opencv_installation_error](https://user-images.githubusercontent.com/57766572/76930065-a0b51480-690b-11ea-9ede-21c42a8b717f.png)

please help me to resolve this issue

**Comment by hmaarrfk** [comment]
Be careful installing things in base. That is conda's environment and you should always use a different one

**Comment by hmaarrfk** [comment]
At least I recommend that

**Comment by Krisanu029** [comment]
I have installed OpenCV using the following snippet on IPython console screen:

!pip install opencv-python==3.4.2.17  

is the above code snippet right?

**Comment by mshabunin** [comment]
@Krisanu029 , no, it is not right. This snippet install OpenCV from pip repository (https://pypi.org/project/opencv-python/) and this is issue tracker for OpenCV package in conda-forge conda channel (https://conda-forge.org/ ; https://anaconda.org/conda-forge/opencv).
As @hmaarrfk  wrote it is recommended to install packages to separate conda environment:
```.sh
conda install -n my-env-for-cv -c conda-forge opencv <other-packages-you-need>
conda activate my-env-for-cv
```
Otherwise all packages will be installed into default `base` environment which can cause conflicts and problems.
