### ISSUE TITLE
add ffmpeg support

### ISSUE THREAD

**Issue by cailiang9** [conda-forge/opencv-feedstock#72]

**Comment by jakirkham** [comment]
This already exists in the latest version. Please make sure you are updated. If it has some problems, please open a new issue with details about the problems encountered.

**Comment by cailiang9** [comment]
I updated and use ldd to see if cv2.so linked to libav*.so. Found nothing. So what did you mean that ffmpeg is already supported?

**Comment by patricksnape** [comment]
You are correct, the builds failed silently - seems the issue is:

  1. conda-forge FFMPEG is built with libavresample - trying to fix [here](https://github.com/conda-forge/ffmpeg-feedstock/pull/31)
  2. [This test](https://github.com/conda-forge/opencv-feedstock/blob/master/recipe/test_ffmpeg.py) doesn't actually get run and needs to be run to check video loading works

**Comment by patricksnape** [comment]
This should be fixed now since that test passed in #75. So please confirm it's fixed (in about 2 hours) and then we can close this
