### ISSUE TITLE
Optional CUDA-supported build

### ISSUE THREAD

**Issue by magsol** [conda-forge/opencv-feedstock#74]
Hi all,

This is more of a "conda-forge protocol" question--I'm interested in slightly altering the `build.sh` script in this feedstock to turn on CUDA support. Obviously this isn't something you want in the master branch, but it would be nice if I didn't have to keep pulling down changes and re-editing the build script every time this feedstock is updated. What is the preferred way to incorporate this change into the conda-forge package?

**Comment by jakirkham** [comment]
We should try to get some feedback from Continuum about how they handle existing GPU-enabled packages. That way if we do make change here to support outside builds for GPUs, it doesn't break what Continuum is trying to do. If someone on the Continuum end could help us with the nitty gritty details of how things are packaged in `defaults`, that would be really helpful in figuring out how to move forward.

cc @jjhelmus @msarahan

**Comment by jjhelmus** [comment]
Currently at Continuum we are making separate `-gpu` packages for projects that support that option.  For example `tensorflow` and `tensorflow-gpu`.  This is not ideal since it is possible to install both into an environment with the second package clobbering the first.  Additionally, all packages which depend on these must also come in a `-gpu` and standard version.  We are investigating better ways for providing these two versions.

As for the actual building, most of this is done inside a docker container with the necessary NVIDIA tools and libraries installed.  Specifically, I've been using the [`pkg_build_nvidia_centos6_dt2`](https://github.com/jjhelmus/docker-images/tree/master/pkg_build_nvidia_centos6_dt2) container.  Running this with [`nvidia-docker`](https://github.com/NVIDIA/nvidia-docker) allows access to the GPU on the host system when that is needed.

As far as I know, there are no plans at the moment for Continuum to provide a CUDA enhanced OpenCV.

**Comment by magsol** [comment]
No worries about Continuum's plans, I was just curious if this was something I could do myself via conda-forge without running into the problems you described (clobbering the non-GPU version; duplicating all the dependencies; basically creating two parallel, mostly-identical packages that have be separately maintained).

For now I'll just keep a few scripts that pull down the non-GPU version, automatically edit the build script, and locally build a GPU-enabled version. Thanks!

**Comment by austinmw** [comment]
Are there still no plans for CUDA enhanced OpenCV for conda?

**Comment by jakirkham** [comment]
Please move this discussion to issue ( https://github.com/conda-forge/conda-forge.github.io/issues/63 ). Once conda-forge settles on a solution for this OpenCV can adopt it.
